### ISSUE TITLE
Using another OMOP v5 DB than the smart-postgresql

### ISSUE THREAD

**Issue by ckamann** [gt-health/GT-FHIR2#63]
Hey there,

is it possible to use another another OMOP v5 DB than the smart-postgresql db you provide? I checked the differences between the smart-postgresql schema and the usual one and obviously only the f_* tables and smart_* tables differ. You also stated that in the readme "To support GT-FHIR, f_* table/view exist. To support context holder, some smart_* tables exists." What changes do i have to perform on my omop v5 db to create those f_* / smart_* tables to work with GT-FHIR2? And why do you use those tables in the first place? I could not find any info in the documentation. I hope you can help me with this issue.

Greetings from Germany!

**Comment by myungchoi** [comment]
Hi, Christian,

Yes, you can use other OMOP v5 DB. We intact uses different tables for our OMOPonFHIR instances.  f_*table and view are required. f_person table is to hold patient demographic information. Since OMOP is for analytics, the person table does not have columns for such information. Our approach is not to change the existing tables as much as we can. So, we decided to create f_* table to hold FHIR related data that do not exist in OMOP tables.

The view table combines observation and measurement tables. In FHIR, we only have an Observation resource. With view that combine these two tables, we can do easy queries. When we write, we individually connect to original tables.

Hope this answers your question.
