### ISSUE TITLE
Using postgreSQL instead of smart-postdreSQL

### ISSUE THREAD

**Issue by sohrabhejazi** [gt-health/GT-FHIR2#65]
Hi,

I am trying to use the GT-FHIR2 to convert our OMOP data on FHIR. We have an OMOP (v5) server which supports PostgreSQL. As I read in the last issue, you added some new tables to DB like f_person,... I call them "smart tables".
I have a question about your program:
Is it possible to use your program without smart tables? (I prefer to convert my OMOP data without modifying them)
If yes, could you please guide me and tell me how? 
If no, Is it possible to add ourself these tables in our DB to use your program? How we can add them? Do you have any suggestion or example?

Thank you in advance,
Sohrab

**Comment by myungchoi** [comment]
You can use your postgreSQL. There are one table and one view that need to exist for the omoponfhir to work. They are f_person and f_observation_view. This can be created by you. The CREATE scripts can be obtained from smart-postgreSQL using any postgreSQL tool. 

Other extra tables are not necessary for FHIR operation. Those are there for SMART on FHIR support, which needs other systems to function such as OAuth server.

However, if you set the DDL option in omopv5-stu3-server project to update or create, those tables will be created automatically by JPA module. So, you may just use your postgresql and set the DDL option to create the tables for you. f_observation_view may need to be created manually (as I am not sure if jpa/hibernate can create a view).

What's more important is the content of f_person. f_person table MUST have the matching entry for all the rows in person table. We ETL to populate with random names. I will ask the author if it's OK to share the ETL here. 

And, please note that OmopOnFHIR does not alter any of your data. This is why we created f_* table and view so that people can persist their original data and tables. Creating extra tables won't affect your existing operations.

**Comment by sohrabhejazi** [comment]
We added them to DB, but we get the following error when we try to search a patient via FHIR UI:

>  Error: HTTP 500 : Unable to find edu.gatech.chai.omopv5.model.entity.Location with id 1

**Comment by sohrabhejazi** [comment]
Thank you very much for your help.
